name: Nightly

on:
  schedule:
    - cron: "8 0 * * *"

  workflow_dispatch:

jobs:
  check_memfault_help:
    runs-on: ubuntu-latest
    container:
      image: python:3.10

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Latest Memfault CLI
        run: |
          pip install --upgrade memfault-cli
          memfault --version

      - name: Verify Memfault CLI Help
        run: |
          echo '```text
          $ memfault --help' > help.txt

          CI=1 memfault --help >> help.txt

          echo '
          ```' >> help.txt

          diff -duw help.txt src/pages/_partials/_memfault-cli-help.mdx

  run-if-failed:
    runs-on: ubuntu-latest
    needs: [check_memfault_help]
    if: |
      always() && (
      needs.check_memfault_help.result == 'failure'
      )

    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_COLOR: failure
          SLACK_USERNAME: docs-nightly
          SLACK_ICON_EMOJI: ":boom:"
          MSG_MINIMAL: "actions url"
          SLACK_MESSAGE:
            "Memfault CLI help is out of date for memfault/memfault-docs!"
